### ISSUE TITLE
Please share an example of how to use this module?

### ISSUE THREAD

**Issue by deweydb** [yhenon/pyimgsaliency#1]
I'm a bit lost, how do we use this module? thank you!

**Comment by yhenon** [comment]
Hi,
I've added a simple example here:

https://github.com/yhenon/pyimgsaliency/blob/master/pyimgsaliency/demo.py

Any aspect in particular you are interested in ?

**Comment by deweydb** [comment]
Thank you very much!  This is extremely helpful.
