### ISSUE TITLE
LinAlgError due to Singular Matrix

### ISSUE THREAD

**Issue by Make42** [yhenon/pyimgsaliency#2]
With some images the algorithm

```
import saliency_triple as psal
psal.get_saliency_mbd(filename).astype('uint8')
```

throws an `LinAlgError` in

```
cov_left = np.linalg.inv(cov_left)
cov_right = np.linalg.inv(cov_right)

cov_top = np.linalg.inv(cov_top)
cov_bottom = np.linalg.inv(cov_bottom)
```

since one of `cov_`... can be singular. Using `np.linalg.pinv` does not work - the saliency map becomes solely black. I do not understand the algorithm good enough to improve one that. Could you please?

**Comment by yhenon** [comment]
Hi,
Could you share an image that causes this issue? Thanks.

**Comment by Make42** [comment]
Yes. These images caused the issue:

![4837__small_nio_color](https://cloud.githubusercontent.com/assets/4905185/24265104/aafe9048-1002-11e7-92b1-42f51709c9f1.jpg)
![4837__small_io_color](https://cloud.githubusercontent.com/assets/4905185/24265109/b027a55a-1002-11e7-8345-d55921fc092a.jpg)

Please try both.

**Comment by Make42** [comment]
No progress?

**Comment by yhenon** [comment]
Hi,
I haven't been able to replicate this issue. Using your image as `test1.jpg`

	import pyimgsaliency as psal
	import cv2

	filename = 'test1.jpg'

	mbd = psal.get_saliency_mbd(filename).astype('uint8')
	rbd = psal.get_saliency_rbd(filename).astype('uint8')

	cv2.imwrite('mbd.png',mbd)
	cv2.imwrite('rbd.png',rbd)

Succesfully saves the images to disk (note that these algos are not designed for medical images, results may not be the best).


![rbd](https://cloud.githubusercontent.com/assets/9943242/24868824/535881a6-1ddf-11e7-926d-50d52b465280.png)

![mbd](https://cloud.githubusercontent.com/assets/9943242/24868819/4d250ed0-1ddf-11e7-88f9-103a80540c54.png)

Can you please check that your packages are up to date (numpy, scipy and sklearn)? Can you also see if the source image is in a stange format (this does happen with medical images)? Input should be 8-bit RGB images.
